#pragma config(Sensor, in1,    gs,             sensorGyro)
#pragma config(Motor,  port1,           w1,            tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           w2,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           w9,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          w10,           tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#pragma platform(VEX2)
#pragma competitionControl(Competition)
#include "Vex_Competition_Includes.c"
void pre_auton(){}

//values for the sensor range from 3600 to -3600. it's calculated by degrees of 10 (10degrees = 100, 90degrees = 900, etc)
//positive numbers(0-3600) are counterclockwise
//negative numbers(-3600-0) are clockwise

//____________________VOID.FUNCTIONS_________________//
//____________________VOID.FUNCTIONS_________________//
//____________________VOID.FUNCTIONS_________________//

void pause(int mSec)
{
	motor[w1]= 0;
	motor[w2]= 0;
	motor[w9]= 0;
	motor[w10]= 0;
}

void initial(int mSec)
{
	SensorType[gs] = sensorNone;
	SensorType[gs] = sensorGyro;
}

void forward(int speed, int mSec)
{
	motor[w1]= speed;
	motor[w2]= speed;
	motor[w9]= speed;
	motor[w10]= speed;
}

void left(int degrees10)
{
	while(abs(SensorValue[gs]) < degrees10)
	{
	motor[w1]= 127;
	motor[w2]= 127;
	motor[w9]= -127;
	motor[w10]= -127;
	}
}

//____________________AUTONOMOUS_____________________//
//____________________AUTONOMOUS_____________________//
//____________________AUTONOMOUS_____________________//

task autonomous()
{
initial(100);
pause(100);
forward(127, 500);
left(900);
}//autonomous


//____________________USERCONTROL____________________//
//____________________USERCONTROL____________________//
//____________________USERCONTROL____________________//

task usercontrol()
{
  while (true)
  {
    UserControlCodePlaceholderForTesting();
  }//while
}//usercontrol
