#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  WC1,            sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  WC2,            sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  WC3,            sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_4,  WC4,            sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           WHEEL1,        tmotorVex393HighSpeed_HBridge, openLoop, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port2,           WHEEL3,        tmotorVex393HighSpeed_MC29, openLoop, encoderPort, I2C_3)
#pragma config(Motor,  port9,           WHEEL2,        tmotorVex393HighSpeed_MC29, openLoop, encoderPort, I2C_2)
#pragma config(Motor,  port10,          WHEEL4,        tmotorVex393HighSpeed_HBridge, openLoop, reversed, encoderPort, I2C_4)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)
#pragma competitionControl(Competition)
#include "Vex_Competition_Includes.c"
//one more encoder rotation of a speed motor is 392 (392 = 1.05ft)
//one full rotation is 1.05	feet for omniwheels
// 1' 11/12" --- 23" : 1 block on square
//100-RPM
//715.68 = 1 SQUARE

//------------------------------------------------------------------------------------------------//
////////////////////////////////////////////////////////////////////////////////////////////////////
// establish "master" encoder for daisy chain
// I2C sensor - Quadratic Encoder
// make sure to set up with motors
////////////////////////////////////////////////////////////////////////////////////////////////////
//------------------------------------------------------------------------------------------------//

//standard format
	void forward (int x)
	{
		while((nMotorEncoder[WC1] < x) && (nMotorEncoder[WC2] < x) && (nMotorEncoder[WC3] < x) && (nMotorEncoder[WC4] < x))
		{
		motor[WHEEL1] = 127;
		motor[WHEEL2] = 127;
		motor[WHEEL3] = 127;
		motor[WHEEL4] = 127;
		}
	}

//NEED an encoder pause
	void eencoder_pause ()
	{
		nMotorEncoder[WC1] = 0;
		nMotorEncoder[WC2] = 0;
		nMotorEncoder[WC3] = 0;
		nMotorEncoder[WC4] = 0;
	}

//if encoder values are negative:

	//option 1-
	void reverse (int x)
	{
	while((nMotorEncoder[WC1] < x) && (nMotorEncoder[WC2] < x) && (nMotorEncoder[WC3] < x) && (nMotorEncoder[WC4] > x))
		{
		motor[WHEEL1] = -127;
		motor[WHEEL2] = -127;
		motor[WHEEL3] = -127;
		motor[WHEEL4] = -127;
		}
	}

	//option 2-
	void turn_left (int x)
	{
		while ((abs(nMotorEncoder[WC1] < x) || (abs(nMotorEncoder[WC2] < x) || (abs(nMotorEncoder[WC3] < x) || {abs(nMotorEncoder[WC4] < x)))
		{
		motor[WHEEL1] = 127;
		motor[WHEEL3] = 127;
		motor[WHEEL2] = -127;
		motor[WHEEL4] = -127;
		}
	}

task pre_auton()
{}

//------------------------------------------------------------------------------------------------//
//------------------------------------------------------------------------------------------------//
//--------------------------------------AUTONOMOUS------------------------------------------------//
//----------------------------------NOVEMBER 10, 2016---------------------------------------------//
//------------------------------------------------------------------------------------------------//
task autonomous()
//add number value to parameter
//no timing
//start and end with pause functions just in case
{
		encoder_pause();
		pause_forward();
		forward(110);
		encoder_pause();

		pause_forward();
		wait1Msec(10);

		forward(715);
		encoder_pause();

		pause_forward();
		wait1Msec(100);

		turn_left(50);
		encoder_pause();
		pause_forward();
}

//------------------------------------------------------------------------------------------------//
//------------------------------------------------------------------------------------------------//
//--------------------------------------USERCONTROL-----------------------------------------------//
//------------------------------------NOVEMBER 9, 2016--------------------------------------------//
//------------------------------------------------------------------------------------------------//
task usercontrol()
{
}
// reference v.4 YEAR1
