#pragma config(Motor,  port3,           BAR1,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           BAR2,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           BAR3,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           BAR4,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           BAR5,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           BAR6,          tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)
#pragma competitionControl(Competition)
#include "Vex_Competition_Includes.c"
const short leftButton = 1;
const short centerButton = 2;
const short rightButton = 4;
int count = 0;


//automatically assigned in UART serial port, but check port # anyway for wiring

//------------------------------------------------------------------------------------------------//
//------------------------------------LCD-SETUP---------------------------------------------------//
//------------------------------------------------------------------------------------------------//
void waitForPress()
{
	while(nLCDButtons == 0){}
}

void waitForRelease()
{
	while(nLCDButtons != 0){}
}

void pre_auton()
{
	clearLCDLine(0);
	clearLCDLine(1);
	while((nLCDButtons != centerButton) && (bIfiRobotDisabled))
	{
		switch(count)
		{
		case 0:
			displayLCDCenteredString(0, "1: CUBE LEFT");
			displayLCDCenteredString(1, "<		 Enter		>");
			waitForPress();
			if(nLCDButtons == leftButton)
			{
				waitForRelease();
				count = 3;
			}//if
			else if(nLCDButtons == rightButton)
			{
				waitForRelease();
				count++;
			}//else if
			break;
		case 1:
			displayLCDCenteredString(0, "2: CUBE RIGHT");
			displayLCDCenteredString(1, "<		 Enter		>");
			waitForPress();
			if(nLCDButtons == leftButton)
			{
				waitForRelease();
				count++;//--
			}//if
			else if(nLCDButtons == rightButton)
			{
				waitForRelease();
				count++;
			}//else if
			break;
		case 2:
			displayLCDCenteredString(0, "3: SKILLS");
			displayLCDCenteredString(1, "<		 Enter		>");
			waitForPress();
			if(nLCDButtons == leftButton)
			{
				waitForRelease();
				count--;
			}//if
			else if(nLCDButtons == rightButton)
			{
				waitForRelease();
				count = 0;
			}//else if
			break;
		default:
			count = 0;
			break;
		}//switch
	}//while
}//preauton

//------------------------------------------------------------------------------------------------//
//--------------------------------------VOID-COMMANDS---------------------------------------------//
//------------------------------------------------------------------------------------------------//
		void bar_u()
		{
			motor[BAR1] = -67;
			motor[BAR2] = -67;
			motor[BAR3] = -67;
			motor[BAR4] = -67;
			motor[BAR5] = -67;
			motor[BAR6] = -67;
		}

		void bar_d()
		{
			motor[BAR1] = 127;
			motor[BAR2] = 127;
			motor[BAR3] = 127;
			motor[BAR4] = 127;
			motor[BAR5] = 127;
			motor[BAR6] = 127;
		}

		void bar_pause()
		{
			motor[BAR1] = 0;
			motor[BAR2] = 0;
			motor[BAR3] = 0;
			motor[BAR4] = 0;
			motor[BAR5] = 0;
			motor[BAR6] = 0;
		}

//------------------------------------------------------------------------------------------------//
//----------------------------------AUTONOMOUS----------------------------------------------------//
//------------------------------------------------------------------------------------------------//

task autonomous()
{
	clearLCDLine(0);
	clearLCDLine(1);
	switch(count)
	{
	case 0:
		displayLCDCenteredString(0, "1: LEFT");
		displayLCDCenteredString(1, "is running!");

		//--------------------------------------------------------------------------------------------//
		//--------------------------------CUBE-LEFT---------------------------------------------------//
		//--------------------------------------------------------------------------------------------//

		bar_pause();
		wait1Msec(200);

		bar_u();
		wait1Msec(600);

		bar_pause();
		wait1Msec(500);

		//--------------------------------------------------------------------------------------------//

	break;

	case 1:
		displayLCDCenteredString(0, "2: RIGHT");
		displayLCDCenteredString(1, "is running!");

		//--------------------------------------------------------------------------------------------//
		//------------------------------CUBE-RIGHT----------------------------------------------------//
		//--------------------------------------------------------------------------------------------//

		bar_pause();
		wait1Msec(200);

		bar_u();
		wait1Msec(600);

		bar_pause();
		wait1Msec(500);

		//--------------------------------------------------------------------------------------------//

	break;

		//--------------------------------------------------------------------------------------------//
		//-------------------------------SKILLS-------------------------------------------------------//
		//--------------------------------------------------------------------------------------------//

		case 2:
		displayLCDCenteredString(0, "3: SKILLS");
		displayLCDCenteredString(1, "is running!");

		//--------------------------------------------------------------------------------------------//

		bar_pause();
		wait1Msec(20);

		bar_u();
		wait1Msec(900);

		bar_pause();
		wait1Msec(20);

		//--------------------------------------------------------------------------------------------//

		break;
	default:
		displayLCDCenteredString(0, "No choice");
		displayLCDCenteredString(1, "was made!");
		break;
	}//switch
}//autonomous

//------------------------------------------------------------------------------------------------//
//------------------------------------USERCONTROL-------------------------------------------------//
//------------------------------------------------------------------------------------------------//

task usercontrol()
{
  while (true)
  {
    UserControlCodePlaceholderForTesting();
  }
}
//reference - v.11 - YEAR1
