#pragma config(Sensor, dgtl3,  limit,          sensorTouch)
#pragma config(Motor,  port3,           BAR1,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           BAR2,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           BAR3,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           BAR4,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           BAR5,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           BAR6,          tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)
#pragma competitionControl(Competition)
#include "Vex_Competition_Includes.c"c

//digital sensor
//type - "touch"

//----------------------------------VOID COMMAND--------------------------------------------------//
void barlim()
		{
		if(SensorValue[dgtl2] == 1)
			{
			motor[BAR1] = 0;
			motor[BAR2] = 0;
			motor[BAR3] = 0;
			motor[BAR4] = 0;
			motor[BAR5] = 0;
			motor[BAR6] = 0;
  		}
 		}
//------------------------------------------------------------------------------------------------//
//----------------------------------AUTONOMOUS----------------------------------------------------//
//------------------------------------------------------------------------------------------------//

task autonomous()
{
		barlim(); //no set parameter

		bar_u();
		wait1Msec(500);

}
//------------------------------------------------------------------------------------------------//
//------------------------------------USERCONTROL-------------------------------------------------//
//------------------------------------------------------------------------------------------------//
task usercontrol()
{

  while (true)
  {
//------------------------------------------------------------------------------------------------//
//------------------------------------------------------------------------------------------------//
  	//------------------------------LIMIT-SWITCH-0------------------------------------------------//
  	if(SensorValue[dgtl2] == 0) //situation if limit switch is not pressed
  {
		//----------------------------LIFT-WITH-HOLDING-POWER-----------------------------------------//
		if ((vexRT[Btn6U] == 0) && (vexRT[Btn6D] == 0 ))
		{
			motor[BAR1] = motor[BAR2] = motor[BAR3] = motor[BAR4] = motor[BAR5] = motor[BAR6] = -10;
		}//if
			else if ((vexRT[Btn6U] == 1) && (vexRT[Btn6D] == 1 ))

			motor[BAR1] = motor[BAR2] = motor[BAR3] = motor[BAR4] = motor[BAR5] = motor[BAR6] = 0;
		}//else if
			else
		{
			motor[BAR1] = motor[BAR2] = motor[BAR3] = motor[BAR4] = motor[BAR5] = motor[BAR6] = + (vexRT[Btn6D] * 127) - (vexRT[Btn6U] * 127);
		} //else
	}//if

//------------------------------------------------------------------------------------------------//
//------------------------------------------------------------------------------------------------//
		//----------------------------------LIMIT-SWITCH=1--------------------------------------------//
		if(SensorValue[dgtl2] == 1)//situation if limit swtich is pressed
  	{

		//-------------------------LIFT-WITH-HOLDING-POWER--------------------------------------------//
		if ((vexRT[Btn6U] == 0) && (vexRT[Btn6D] == 0 ))
		{
			motor[BAR1] = motor[BAR2] = motor[BAR3] = motor[BAR4] = motor[BAR5] = motor[BAR6] = -10;
		}
			else if ((vexRT[Btn6U] == 1) && (vexRT[Btn6D] == 1 ))
		{
			motor[BAR1] = motor[BAR2] = motor[BAR3] = motor[BAR4] = motor[BAR5] = motor[BAR6] = 0;
		}
			else
		{
			motor[BAR1] = motor[BAR2] = motor[BAR3] = motor[BAR4] = motor[BAR5] = motor[BAR6] = + (vexRT[Btn6D] * 127) - (vexRT[Btn6U] * 0);
		}//else
	 }//if
  }//while
 }// task

 //reference - v.9 - YEAR1
