#pragma config(Sensor, dgtl1,  pneu,           sensorDigitalOut)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)
#pragma competitionControl(Competition)
#include "Vex_Competition_Includes.c"

//digital sensor
//type - digital out

void pre_auton()
{
  bStopTasksBetweenModes = true;
}

task autonomous()
{
  AutonomousCodePlaceholderForTesting();
}

//------------------------------------------------------------------------------------------------//
//------------------------------------USERCONTROL-------------------------------------------------//
//------------------------------------------------------------------------------------------------//

task usercontrol()
{

  while (true)
  {
		//----------------------------------PNEUMATICS------------------------------------------------//
		{
		   if(vexRT[Btn8U] == 1) 								// 8U PRESSED = PISTON IN
		   {
		     SensorValue[pneu] = 1;
	    }
	    else if(vexRT[Btn8R] == 1)						// 8R PRESSED PNEU = PISTON OUT
	    {
		     SensorValue[pneu] = 0;
		   }
		 }//else if
	}//while
}// task

//reference - v.8 - YEAR1
